// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJrBa5gATE_COW_vtFWGIb59tiOPAfhaE',
    appId: '1:622093694760:web:c5dfe01489c224706f021d',
    messagingSenderId: '622093694760',
    projectId: 'chatapp-c89a7',
    authDomain: 'chatapp-c89a7.firebaseapp.com',
    storageBucket: 'chatapp-c89a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsTo296o-KWMAF2z-R0n9wtbMNula1cw8',
    appId: '1:622093694760:android:702a12e0a3562c476f021d',
    messagingSenderId: '622093694760',
    projectId: 'chatapp-c89a7',
    storageBucket: 'chatapp-c89a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNeclT2Dp91ONDNG6G6zCngBFuZYkTx4',
    appId: '1:622093694760:ios:30a61badec2ed0996f021d',
    messagingSenderId: '622093694760',
    projectId: 'chatapp-c89a7',
    storageBucket: 'chatapp-c89a7.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdNeclT2Dp91ONDNG6G6zCngBFuZYkTx4',
    appId: '1:622093694760:ios:30a61badec2ed0996f021d',
    messagingSenderId: '622093694760',
    projectId: 'chatapp-c89a7',
    storageBucket: 'chatapp-c89a7.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJrBa5gATE_COW_vtFWGIb59tiOPAfhaE',
    appId: '1:622093694760:web:6dccc535f312d5ef6f021d',
    messagingSenderId: '622093694760',
    projectId: 'chatapp-c89a7',
    authDomain: 'chatapp-c89a7.firebaseapp.com',
    storageBucket: 'chatapp-c89a7.firebasestorage.app',
  );
}
